DROP TABLE IF EXISTS members CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  avatar VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);